config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do 
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :edit, :update]

  get 'users/:id/newpass', to: 'users#newpass', as: :newpass_user

  patch 'users/:id/update_password', to: 'users#update_password', as: :update_password

  resource :session, only: [:new, :destroy, :create]


end

app/models/ability.rb
class Ability
    include CanCan::Ability

  def initialize(user)

    user ||= User.new #guest user (not logged in)

    if user.admin?
        can :manage, :all
    elsif user.present?
        can :create, :update, :destroy, :all
    else
        can :read, :all
    end



    alias_action :create, :read, :update, :delete, :to => :crud

    can :crud, Post do |post|
        user == post.user
      end
  
    can :crud, Comment do |comment|
        user == comment.user 
    end
  
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    
    def user_signed_in?
        current_user.present?
    end
        helper_method :user_signed_in?

        helper_method :current_user
      
    private

    def authenticate_user!
        redirect_to new_session_path, alert: "Please sign in" unless user_signed_in?
    end

    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
        
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index]
    before_action :find_post
    #before_action :authorize_user!, only:[:edit, :update, :destroy]

    def create
        @comment = Comment.new(comment_params)
        @comment.post = @post
        @comment.user = current_user
        if @comment.save
            flash[:success] = "Comment successfully created"
            redirect_to post_path(@post)
        else
            @comments = @post.comments.order(created_at: :desc)
            render '/posts/show'
        end
    end

    def destroy
        @comment = Comment.find params[:id]
        if can?(:crud, @comment)
            @comment.destroy
            redirect_to post_path(@post)
            flash[:success] = "Comment deleted"
        elsif can?(:crud, @post)
        @comment.destroy
        redirect_to post_path(@post)
        flash[:success] = "Comment deleted"
        else   
            redirect_to post_path, alert: "Not athorized to change Comment!"
        end
    end

    private
    def find_post
        @post = Post.find params[:post_id]
    end
    
    def comment_params
        params.require(:comment).permit(:body)
    end

    # def authorize_user!
    #     redirect_to posts_path, alert: "Not authorized!" unless can?(:crud, @comment)
    # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only:[:edit, :update, :destroy]

    def index
      @posts = Post.order(created_at: :desc)
    end

    def new
      @post = Post.new
      
    end

    def create
      @post = Post.new(post_params)
      @post.user = current_user
      if @post.save
        flash[:success] = "Post successfully created"
        redirect_to @post
      else
        flash[:error] = "Something went wrong"
        render 'new'
      end
    end
    
    def show
      @comment = Comment.new
    end

    def edit
      
    end

    def update
      if @post.update(post_params)
          flash[:success] = "Post successfully updated"
          redirect_to @post
        else
          flash[:error] = "Something went wrong"
          render :edit  
        end
    end  
    
    def destroy
      @post.destroy
      redirect_to posts_path
    end
    
    private

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def find_post
        @post = Post.find params[:id]
    end

    def authorize_user!
      redirect_to root_path, alert: "Not authorized!" unless can?(:crud, @post)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      @user = User.find_by_email params[:email]
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Logged in"
      else
        flash[:alert] = "Wrong email or password"
        render :new
      end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :newpass]

  def show
    # @user = User.find(params[:id])
  end  
  
  def new
        @user = User.new
      end
    
    def create
        @user = User.new user_params
        if @user.save
          session[:user_id] = @user.id
          redirect_to root_path, notice: "Logged In!"
        else
          render :new
        end
    end

    def edit
      # @user = User.find(params[:id])
    end
    
    def update
      # @user = User.find(params[:id])
      if @user.update(edit_user_params)
        flash[:success]
      else
        flash[:alert] = user.errors.full_messages.join(", ")
      end
      redirect_to posts_path
    end

    def newpass
      # @user = User.find(params[:id])
    end

    def update_password
      @user = User.find(params[:id])
      if @user.authenticate(params[:user][:current_password])
        @user.update(password: params[:user][:new_password], password_confirmation: params[:user][:new_password_confirmation])
        if @user.valid?
          flash[:success]= "password changed"
          redirect_to posts_path
        else
          flash[:alert]= user.errors.full_messages.join(", ")
          redirect_to newpass_user_path
        end
      end
    end

    private
    
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(
          :first_name,
          :last_name,
          :email,
          :password,
          :password_confirmation
        )
    end

    def edit_user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email
      )
    end

    def password_params
      params.require(:user).permit(
        :current_password,
        :password,
        :password_confirmation,
        :id
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
 Hello <%= link_to current_user.first_name, edit_user_path(current_user)%> 
    <%= button_to "Logout", session_path, method: :delete,
            data: {confirm: "are you sure you want to log out?"}%>
  <% else %>
    <%= link_to "Login", new_session_path %> |
    <%= link_to "Sign Up", new_user_path %>
  <% end %>
  <hr>
  <% flash.each do |type, message| %>
      <div class="alert alert-info" role=alert >
        <%= type + "-------" + message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title, size: 50 %>
  </div>
  <div>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body, :size=>"50" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/posts/_navBar.html.erb
  <nav class="navbar navbar-expand-med navbar-light bg-light">
    <a class="navbar-brand" href="./"> Blog On Rails
    </a>

  <div class=" navbar navbar-expand ">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/posts" style="color: black ;">Home</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/posts/new" style="color: black ;">New Post</a>
        </li>

      
    </ul>
  
  </div>
</nav>

app/views/posts/edit.html.erb
<%= render "navBar" %>

<%= render "form" %>

app/views/posts/index.html.erb
<%= render "navBar" %>

<div class="card-columns" >
  <% @posts.each do |post| %>
    <div class="card ">
      <div class="card-body">
        <h5 class="card-title"><%= link_to post.title, post %></h5>
        <p class="card-text"><%= post.body %></p>
      </div>    
    </div>  
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render "navBar" %>

<%= render "form" %>

app/views/posts/show.html.erb
<%= render "navBar" %>

<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<p>Created <%= time_ago_in_words(@post.created_at) %> ago </p>

<% if can? :crud, @post %>
  <%= button_to "Edit", edit_post_path(@post), method: :get%>
  <%= button_to "Delete", post_path(@post.id), method: :delete, data: {confirm: "Are you sure"} %></p>
<% end %>

<% @post.comments.each do |com| %>
    <%= com.body %>
    <p>Created <%= time_ago_in_words(com.created_at) %> ago 
    <% if can? :crud, com %>
      <%= link_to 'Delete',  post_comment_path(@post.id, com.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <% end %>
    </p>
    <hr>
<% end %>
 
<%= @comment.errors.full_messages.join(', ') %>
<%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :body %>
    <br>
    <%= f.submit %>
<% end %>

app/views/users/_navBar.html.erb
  <nav class="navbar navbar-expand-med navbar-light bg-light">
    <a class="navbar-brand" href="./"> Blog On Rails
    </a>

  <div class=" navbar navbar-expand ">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/posts" style="color: black ;">Home</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/posts/new" style="color: black ;">New Post</a>
        </li>

      
    </ul>
  
  </div>
</nav>

app/views/users/edit.html.erb
<%= render "navBar" %>
<h1>Edit</h1>

 <% if @user.errors.any? %>
  <ul>
     <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
    <% end %>
  </ul>
 <% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= link_to "Change Password", newpass_user_path(current_user)%> 
  </div>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= render "navBar" %>
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>

app/views/users/newpass.html.erb
<%= render "navBar" %>
<h1>Reset Password</h1>

<%= form_for @user, url: update_password_path(@user) do |f| %>
  <div>
    <%= f.label :current_password %>
    <%= f.password_field :current_password %>
  </div>
  <div>
    <%= f.label :new_password %>
    <%= f.password_field :new_password %>
  </div>
    <div>
    <%= f.label :new_password_confirmation %>
    <%= f.password_field :new_password_confirmation %>
  </div>
  <div>
    <%= f.submit%>
  </div>
<% end %>